spring:
  application:
    name: ${SPRING_APP_NAME:springsecsection1}
  datasource:
    url: jdbc:mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:3306}/${DATABASE_NAME:eazybank}
    username: ${DATABASE_USERNAME:user}
    password: ${DATABASE_PASSWORD:123456}
  jpa:
    show-sql: ${JPA_SHOW_SQL:true}
    properties:
      hibernate:
        format_sql: ${HIBERNATE_FORMAT_SQL:true}
  # profiles:
  #   active:
  #   - prod

server:
  servlet:
    session:
      timeout: ${SESSION_TIMEOUT:30s}
      cookie:
        max-age: ${MAX_AGE:30s}

logging:
  level:
    org:
      springframework:
        security: ${SPRING_SECURITY_LOG_LEVEL:TRACE}
  pattern:
    console: ${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss:SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}
